package: spm1d

platform: 
 - linux-64

engine:
 - python=3.4
 - python=3.5
 - python=2.7
script:
  - conda build recipe -c melund 

after_success:
   - conda convert -p all /opt/miniconda/conda-bld/linux-64/spm1d*.tar.bz2 -o /opt/miniconda/conda-bld

after_failure:
   - echo "Build failed!"

build_targets:
   - /opt/miniconda/conda-bld/*/*.tar.bz2
